/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface D09ServiceStatusComponent {
        "apiToCheck": string;
        "offlineColor"?: string;
        "offlineText"?: string;
        "onlineColor"?: string;
        "onlineText"?: string;
        "status": string;
        "statusText"?: string;
    }
}
declare global {
    interface HTMLD09ServiceStatusComponentElement extends Components.D09ServiceStatusComponent, HTMLStencilElement {
    }
    var HTMLD09ServiceStatusComponentElement: {
        prototype: HTMLD09ServiceStatusComponentElement;
        new (): HTMLD09ServiceStatusComponentElement;
    };
    interface HTMLElementTagNameMap {
        "d09-service-status-component": HTMLD09ServiceStatusComponentElement;
    }
}
declare namespace LocalJSX {
    interface D09ServiceStatusComponent {
        "apiToCheck": string;
        "offlineColor"?: string;
        "offlineText"?: string;
        "onlineColor"?: string;
        "onlineText"?: string;
        "status"?: string;
        "statusText"?: string;
    }
    interface IntrinsicElements {
        "d09-service-status-component": D09ServiceStatusComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d09-service-status-component": LocalJSX.D09ServiceStatusComponent & JSXBase.HTMLAttributes<HTMLD09ServiceStatusComponentElement>;
        }
    }
}
